/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdatalanjuut;

/**
 *
 * @author Azzam Wildan
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormBus extends javax.swing.JFrame {

    /**
     * Creates new form FormBus
     */
    private DefaultTableModel tableModel;
    private Connection conn;
    private PreparedStatement ps;
    private ResultSet rs;
    private ArrayList<Bus> BusPilihan = new ArrayList<>();
    
    public FormBus() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClearBus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBus = new javax.swing.JTable();
        btnSelanjutnya = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnPilih = new javax.swing.JButton();
        cbJenisBus = new javax.swing.JComboBox<>();
        btnCariJenisBis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PEMILIHAN BIS");

        jLabel4.setText("Jenis Bus:");

        btnClearBus.setText("Bersih");
        btnClearBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearBusActionPerformed(evt);
            }
        });

        tblBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nopol Bus", "Jenis Bus", "Harga Sewa Per Hari", "Kapasitas", "Status"
            }
        ));
        tblBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBus);

        btnSelanjutnya.setText("Selanjutnya");
        btnSelanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnPilih.setText("Pilih Bis");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        cbJenisBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mini Bus", "Medium Bus", "Big Bus", "Semua Bus" }));
        cbJenisBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisBusActionPerformed(evt);
            }
        });

        btnCariJenisBis.setText("Cari");
        btnCariJenisBis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariJenisBisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74)
                                .addComponent(cbJenisBus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCariJenisBis))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1)))
                        .addGap(0, 264, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPilih)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearBus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelanjutnya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKembali))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariJenisBis)
                    .addComponent(jLabel4)
                    .addComponent(cbJenisBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih)
                    .addComponent(btnClearBus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnSelanjutnya))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Pelanggan formPelanggan = new Pelanggan();
        formPelanggan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
     int selectedRow = tblBus.getSelectedRow();
    if (selectedRow != -1) {
        String nopolBus = tblBus.getValueAt(selectedRow, 0).toString();
        String jenisBus = tblBus.getValueAt(selectedRow, 2).toString();
        int kapasitas = Integer.parseInt(tblBus.getValueAt(selectedRow, 3).toString());
        double hargaSewa = Double.parseDouble(tblBus.getValueAt(selectedRow, 4).toString());
        String status = tblBus.getValueAt(selectedRow, 5).toString();

        if (status.equalsIgnoreCase("tersedia")) {
            // Lanjutkan proses pemilihan bus
            JOptionPane.showMessageDialog(this, "Bus dengan Nopol: " + nopolBus + " dipilih.");
            // Simpan atau gunakan data bus yang dipilih
        } else {
            JOptionPane.showMessageDialog(this, "Bus ini sedang disewa, pilih bus lain.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu!");
    }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void cbJenisBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisBusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbJenisBusActionPerformed

    private void btnClearBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearBusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBus.getModel();
    model.setRowCount(0);
    
    // Reset pilihan jenis bus
    cbJenisBus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearBusActionPerformed

    private void btnSelanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaActionPerformed
        // TODO add your handling code here:
    FormPenyewaan formPenyewaan = new FormPenyewaan();
    
    // Set formPenyewaan menjadi visible
    formPenyewaan.setVisible(true);
    
    // Tutup formBus
    this.dispose();
    }//GEN-LAST:event_btnSelanjutnyaActionPerformed

    private void btnCariJenisBisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariJenisBisActionPerformed
        // TODO add your handling code here:
         String jenisBus = cbJenisBus.getSelectedItem().toString();

    String query = "SELECT NopolBis, jenis_bus, harga_sewa_per_hari, kapasitas, status FROM Bus ";
    if (!jenisBus.equalsIgnoreCase("Semua bus")) {
        query += "WHERE jenis_bus = ?";
    }

    connectDatabase(); // Fungsi untuk koneksi ke database
    try {
        ps = conn.prepareStatement(query);
        if (!jenisBus.equalsIgnoreCase("Semua bus")) {
            ps.setString(1, jenisBus);
        }

        rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) tblBus.getModel();
        model.setRowCount(0); // Hapus baris yang ada

        // Masukkan data ke dalam tabel
        while (rs.next()) {
            Object[] row = {
                rs.getString("NopolBis"),
                rs.getString("jenis_bus"),
                rs.getDouble("harga_sewa_per_hari"),
                rs.getInt("kapasitas"),
                rs.getString("status")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data bus: " + e.getMessage());
    } finally {
        closeConnection(); // Fungsi untuk menutup koneksi database
    }
    }//GEN-LAST:event_btnCariJenisBisActionPerformed

    private void tblBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusMouseClicked
        // TODO add your handling code here:
         int selectedRow = tblBus.getSelectedRow();
        if (selectedRow != -1) {
            // Ambil data dari baris yang dipilih
            String nopolBus = tblBus.getValueAt(selectedRow, 0).toString();
            String jenisBus = tblBus.getValueAt(selectedRow, 1).toString();
            double hargaSewa = Double.parseDouble(tblBus.getValueAt(selectedRow, 2).toString());
            int kapasitas = Integer.parseInt(tblBus.getValueAt(selectedRow, 3).toString());
            String status = tblBus.getValueAt(selectedRow, 4).toString();

            // Simpan data ke variabel atau tampilkan di tempat lain
            System.out.println("Nopol Bus: " + nopolBus);
            System.out.println("Jenis Bus: " + jenisBus);
            System.out.println("Harga Sewa: " + hargaSewa);
            System.out.println("Kapasitas: " + kapasitas);
            System.out.println("Status: " + status);
        }
    }//GEN-LAST:event_tblBusMouseClicked

    private void connectDatabase() {
        try {
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PenjualanTiketBis", "postgres", "azzam2003");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariJenisBis;
    private javax.swing.JButton btnClearBus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnSelanjutnya;
    private javax.swing.JComboBox<String> cbJenisBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBus;
    // End of variables declaration//GEN-END:variables

    private void closeConnection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void loadData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void searchBusByJenis(String selectedJenisBus) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
