/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basisdatalanjuut;

/**
 *
 * @author Azzam Wildan
 */
import javax.swing.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class FormPenyewaan extends javax.swing.JFrame {

    /**
     * Creates new form FormPenyewaan
     */
    private Connection connection;
    

    public FormPenyewaan(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpanPenyewaan = new javax.swing.JButton();
        btnClearPembayaran = new javax.swing.JButton();
        btnKembaliBus = new javax.swing.JButton();
        txtTanggal_Mulai = new javax.swing.JTextField();
        txtHargaTotal = new javax.swing.JTextField();
        cbStatusSewa = new javax.swing.JComboBox<>();
        btnHitungTotalSewa = new javax.swing.JButton();
        btnEditPenyewaan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTanggal_Selesai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtextAreaPenyewa = new javax.swing.JTextArea();
        btnSelanjutnyaPembayaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PENYEWAAN");

        jLabel3.setText("Tanggal Mulai:");

        jLabel4.setText("Total Harga:");

        jLabel5.setText("Status Sewa:");

        btnSimpanPenyewaan.setText("Simpan");
        btnSimpanPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPenyewaanActionPerformed(evt);
            }
        });

        btnClearPembayaran.setText("Bersih");
        btnClearPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPembayaranActionPerformed(evt);
            }
        });

        btnKembaliBus.setText("Kembali");
        btnKembaliBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliBusActionPerformed(evt);
            }
        });

        txtTanggal_Mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggal_MulaiActionPerformed(evt);
            }
        });

        txtHargaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaTotalActionPerformed(evt);
            }
        });

        cbStatusSewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Selesai", "Dibatalkan" }));

        btnHitungTotalSewa.setText("Hitung");
        btnHitungTotalSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungTotalSewaActionPerformed(evt);
            }
        });

        btnEditPenyewaan.setText("Edit");
        btnEditPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPenyewaanActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Selesai:");

        JtextAreaPenyewa.setColumns(20);
        JtextAreaPenyewa.setRows(5);
        jScrollPane1.setViewportView(JtextAreaPenyewa);

        btnSelanjutnyaPembayaran.setText("Selanjutnya");
        btnSelanjutnyaPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelanjutnyaPembayaran)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(btnHitungTotalSewa))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnSimpanPenyewaan)
                                        .addGap(17, 17, 17)
                                        .addComponent(btnEditPenyewaan)
                                        .addGap(19, 19, 19)
                                        .addComponent(btnClearPembayaran))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnKembaliBus)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTanggal_Mulai)
                                                    .addComponent(txtTanggal_Selesai, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                                .addComponent(txtHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbStatusSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggal_Mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTanggal_Selesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbStatusSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitungTotalSewa)
                    .addComponent(btnSimpanPenyewaan)
                    .addComponent(btnEditPenyewaan)
                    .addComponent(btnClearPembayaran))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembaliBus)
                    .addComponent(btnSelanjutnyaPembayaran))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPenyewaanActionPerformed
        // TODO add your handling code here:
     try {
            String query = "INSERT INTO Penyewaan (NIK_pelanggan, NopolBis, tanggal_mulai, tanggal_selesai, total_harga, status_sewa) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = connection.prepareStatement(query); 
            ps.setDate(3, Date.valueOf(txtTanggal_Mulai.getText()));
            ps.setDate(4, Date.valueOf(txtTanggal_Selesai.getText()));
            ps.setDouble(5, Double.parseDouble(txtHargaTotal.getText()));
            ps.setString(6, cbStatusSewa.getSelectedItem().toString());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data penyewaan berhasil disimpan!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPenyewaanActionPerformed

    private void btnClearPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPembayaranActionPerformed
        // TODO add your handling code here:
        txtTanggal_Mulai.setText("");
        txtTanggal_Selesai.setText("");
        txtHargaTotal.setText("");
        cbStatusSewa.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearPembayaranActionPerformed

    private void btnHitungTotalSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungTotalSewaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnHitungTotalSewaActionPerformed

    private void btnEditPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPenyewaanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEditPenyewaanActionPerformed

    private void btnKembaliBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliBusActionPerformed
        // TODO add your handling code here:
        FormBus formBus = new FormBus();
        formBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliBusActionPerformed

    private void txtTanggal_MulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggal_MulaiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTanggal_MulaiActionPerformed

    private void txtHargaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaTotalActionPerformed

    private void btnSelanjutnyaPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaPembayaranActionPerformed
        // TODO add your handling code here:
        FormPembayaran formPembayaran = new FormPembayaran();
    
    // Set formPembayaran menjadi visible
    formPembayaran.setVisible(true);
    
    // Tutup formPenyewaan
    this.dispose();
    }//GEN-LAST:event_btnSelanjutnyaPembayaranActionPerformed
    
    private void connectDatabase() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PenjualanTiketBis", "postgres", "azzam2003");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenyewaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtextAreaPenyewa;
    private javax.swing.JButton btnClearPembayaran;
    private javax.swing.JButton btnEditPenyewaan;
    private javax.swing.JButton btnHitungTotalSewa;
    private javax.swing.JButton btnKembaliBus;
    private javax.swing.JButton btnSelanjutnyaPembayaran;
    private javax.swing.JButton btnSimpanPenyewaan;
    private javax.swing.JComboBox<String> cbStatusSewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtTanggal_Mulai;
    private javax.swing.JTextField txtTanggal_Selesai;
    // End of variables declaration//GEN-END:variables

    private void tampilkanDataPelangganDanBus() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
